### ISSUE TITLE
KONECT Website Showing 500 Internal Privoxy Error

### ISSUE THREAD

**Issue by Snake-Konginchrist** [kunegis/konect-extr#2]
I'm currently having trouble accessing the KONECT website (http://konect.cc/). When attempting to visit the site, I receive a "500 Internal Privoxy Error." Could you please let me know if there is an ongoing issue with the site or if it’s temporarily down for maintenance? Any information would be appreciated.

**Comment by jiaweixiao** [comment]
I have been experiencing the same problem since March of this year.

**Comment by kunegis** [comment]
Unfrotunately, the KONECT website is down and will not be restored again.
